; generated by PrusaSlicer 2.9.4 on 2026-04-19 at 12:46:56 UTC


; Generic print settings recomended by RatRig, you may change them.

; external perimeters extrusion width = 0.65mm
; perimeters extrusion width = 0.65mm
; infill extrusion width = 0.65mm
; solid infill extrusion width = 0.65mm
; top infill extrusion width = 0.65mm
; first layer extrusion width = 0.84mm

M73 P0 R29
;TYPE:Custom
START_PRINT EXTRUDER_TEMP=175 EXTRUDER_OTHER_LAYER_TEMP=175 BED_TEMP=85 START_CHAMBER_TEMP=0 CHAMBER_TEMP=0 TOTAL_LAYER_COUNT=149 X0=123.47 Y0=123.47 X1=176.53 Y1=176.53
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
G1 E-.5 F1800
G1 Z.85 F3000
G1 X127.268 Y126.97 F30000
G1 Z.35 F3000
G1 E.5 F1500
M204 S1500

